source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'8.0'
target 'Screenshot' do
use_frameworks!

pod 'Masonry'
pod 'LBXScan/LBXNative','~> 2.3'
pod 'LBXScan/LBXZXing','~> 2.3'
pod 'LBXScan/LBXZBar','~> 2.3'
pod 'LBXScan/UI','~> 2.3'

end
